-- Script d'insertion généré à partir de Classeur12.csv
-- Assure-toi d'avoir créé la table import_personnel avant d'exécuter ce script.

INSERT INTO import_personnel (PINDIVIDU_ID, NOMFAMILLE, PRENOM, NUMPOSTE) VALUES
  ('16', 'AMAT                                                                            ', 'ROMAIN FLORIAN                                                                  ', '                    '),
  ('17', 'PERARO                                                                          ', 'MICKAEL ERIC MICHEL                                                             ', 'PRODUCTION          '),
  ('18', 'AGUERRE                                                                         ', 'STEPHANE JEAN MICHEL                                                            ', '                    '),
  ('19', 'ARNAL                                                                           ', 'JEAN MARIE                                                                      ', '                    '),
  ('20', 'BAILLY                                                                          ', 'XAVIER MARC JEAN                                                                ', 'PRODUCTION          '),
  ('21', 'BEHEREGARAY                                                                     ', 'JEAN MICHEL                                                                     ', '200                 '),
  ('22', 'BENGOCHEA                                                                       ', 'EMMANUEL                                                                        ', 'PRODUCTION          '),
  ('23', 'BERCAITS                                                                        ', 'FRANCOIS MARIE                                                                  ', 'PRODUCTION          '),
  ('24', 'BERHO                                                                           ', 'INAKI                                                                           ', 'PRODUCTION          '),
  ('25', 'BERROGAIN                                                                       ', 'JEAN BAPTISTE                                                                   ', '242                 '),
  ('26', 'BERTHE                                                                          ', 'OPHELIE JEANNE SUZANNE                                                          ', 'PRODUCTION          '),
  ('27', 'BIDONDO                                                                         ', 'MICKAEL ALEXANDRE                                                               ', 'PRODUCTION          '),
  ('28', 'BIDONDO                                                                         ', 'PIERRE                                                                          ', '247                 '),
  ('29', 'BOULDOIRES                                                                      ', 'MATHIEU                                                                         ', 'R&D                 '),
  ('30', 'BRANKAER                                                                        ', 'ALEXANDRE                                                                       ', 'PRODUCTION          '),
  ('31', 'CAMY                                                                            ', 'ALAIN                                                                           ', 'PRODUCTION          '),
  ('32', 'CASTEX                                                                          ', 'LAURENT CHRISTIAN                                                               ', 'PRODUCTION          '),
  ('33', 'CORDANI                                                                         ', 'JEANMARIE JOSEPH                                                                ', 'PRODUCTION          '),
  ('34', 'CORREIA DOS SANTOS                                                              ', 'JORGE MANUEL                                                                    ', 'PRODUCTION          '),
  ('35', 'COSTA                                                                           ', 'DANIEL                                                                          ', '342                 '),
  ('36', 'COURTIES                                                                        ', 'DORYAN MARC MARCEL                                                              ', 'PRODUCTION          '),
  ('37', 'DAGUERRE                                                                        ', 'PATRICK JEAN CLAUDE                                                             ', '233                 '),
  ('38', 'DAUBAS                                                                          ', 'GEORGES MICHEL                                                                  ', 'PRODUCTION          '),
  ('39', 'DELGADO                                                                         ', 'CEDRIC GERARD CHRISTIAN                                                         ', 'PRODUCTION          '),
  ('40', 'DUHALDE                                                                         ', 'PIERRE SAUVEUR                                                                  ', 'PRODUCTION          '),
  ('41', 'ERRECART                                                                        ', 'SERGE                                                                           ', 'PRODUCTION          '),
  ('42', 'ETCHEVERRY                                                                      ', 'FREDERIC JEANBERNARD DOMINIQUE                                                  ', 'PRODUCTION          '),
  ('43', 'FERNANDES                                                                       ', 'MARIE FRANCOISE                                                                 ', 'LABORATOIRE         '),
  ('44', 'GODFRIN                                                                         ', 'DAVID                                                                           ', '226                 '),
  ('45', 'GOUVERT                                                                         ', 'CAROLINE CATHERINE JOSEPHINE                                                    ', '222                 '),
  ('46', 'GUIMON                                                                          ', 'ALAIN                                                                           ', 'LEADER              '),
  ('47', 'HEUGAS                                                                          ', 'JEREMY                                                                          ', '243/241             '),
  ('48', 'IGLESIAS                                                                        ', 'LUDOVIC MALIK                                                                   ', 'PRODUCTION          '),
  ('49', 'ITURRIA                                                                         ', 'LOIC                                                                            ', 'MAINTENANCE         '),
  ('50', 'JIMENEZ                                                                         ', 'ANDRE                                                                           ', '264                 '),
  ('51', 'JOUMAH                                                                          ', 'HASSAN                                                                          ', '240                 '),
  ('52', 'KERN                                                                            ', 'BERNARD                                                                         ', 'PRODUCTION          '),
  ('53', 'LAC PEYRAS                                                                      ', 'PASCALE                                                                         ', '241                 '),
  ('54', 'LAGOURGUE                                                                       ', 'DIDIER GUILLERMO                                                                ', 'PRODUCTION          '),
  ('55', 'LARRABURU                                                                       ', 'PASCALE                                                                         ', 'LABORATOIRE         '),
  ('56', 'LORDON                                                                          ', 'JEANBAPTISTE                                                                    ', 'PRODUCTION          '),
  ('57', 'MAFFRAND                                                                        ', 'ALEXIS                                                                          ', 'PRODUCTION          '),
  ('58', 'MARQUES                                                                         ', 'PAULINE MARIE ELODIE                                                            ', 'PRODUCTION          '),
  ('59', 'MENDRIBIL                                                                       ', 'ALAIN                                                                           ', 'PRODUCTION          '),
  ('60', 'MOLUS                                                                           ', 'SONIA                                                                           ', 'PRODUCTION          '),
  ('62', 'MOUSTROUS                                                                       ', 'HERVE                                                                           ', 'PRODUCTION          '),
  ('63', 'OLIVIER                                                                         ', 'ALBAN ROGER                                                                     ', '207                 '),
  ('64', 'PEREZ                                                                           ', 'XAVIER                                                                          ', 'PRODUCTION          '),
  ('65', 'POCHELU                                                                         ', 'ANDRE MAURICE                                                                   ', 'PRODUCTION          '),
  ('66', 'RECALT                                                                          ', 'HERVE                                                                           ', '220                 '),
  ('67', 'RECALT                                                                          ', 'JEAN PAUL                                                                       ', '222                 '),
  ('68', 'REINA                                                                           ', 'FREDERIC                                                                        ', '257                 '),
  ('69', 'SALLABERRY                                                                      ', 'JEAN MICHEL                                                                     ', '211                 '),
  ('70', 'SARALEGUI                                                                       ', 'ERIC                                                                            ', 'PRODUCTION          '),
  ('71', 'SARDA                                                                           ', 'MANON MARIE                                                                     ', 'ADMIN               '),
  ('72', 'SEBILO                                                                          ', 'ALLAN GEORGES GERARD                                                            ', 'PRODUCTION          '),
  ('73', 'SICRE                                                                           ', 'PIERRE                                                                          ', '342                 '),
  ('74', 'SIMON                                                                           ', 'THOMAS THIERRY DIDIER                                                           ', 'PRODUCTION          '),
  ('75', 'SOUBIRAN                                                                        ', 'VERONIQUE SOPHIE                                                                ', 'LABORATOIRE         '),
  ('76', 'SUBLIME                                                                         ', 'CYRIL GEORGES ANDRE                                                             ', '208                 ');

INSERT INTO import_personnel (PINDIVIDU_ID, NOMFAMILLE, PRENOM, NUMPOSTE) VALUES
  ('77', 'TARDY                                                                           ', 'JEAN MARIE                                                                      ', 'PRODUCTION          '),
  ('78', 'TRADERE                                                                         ', 'JONATHAN JEAN                                                                   ', 'PRODUCTION          '),
  ('79', 'VASSEUR                                                                         ', 'JOFFREY                                                                         ', 'PRODUCTION          '),
  ('80', 'VERGE                                                                           ', 'OLIVIER                                                                         ', 'PRODUCTION          '),
  ('81', 'VERGE                                                                           ', 'REMY                                                                            ', 'PRODUCTION          '),
  ('82', 'ALTHABE                                                                         ', 'MICHEL                                                                          ', '205                 '),
  ('83', 'ARHANCETEBEHERE                                                                 ', 'DIDIER                                                                          ', '218                 '),
  ('84', 'ARROUGE                                                                         ', 'THOMAS                                                                          ', 'MAITENANCE          '),
  ('85', 'BERGEZ                                                                          ', 'FRANCK                                                                          ', '228                 '),
  ('86', 'CHARMAN                                                                         ', 'MAXIME DANIEL                                                                   ', '214                 '),
  ('87', 'COUCHINIAV                                                                      ', 'SONIA                                                                           ', '202                 '),
  ('88', 'COUCHINIAV                                                                      ', 'ERIC                                                                            ', 'PRODUCTION          '),
  ('89', 'GAUCHET                                                                         ', 'STEVE JEAN RENE                                                                 ', '206                 '),
  ('90', 'GAUDIN                                                                          ', 'ALEXANDRA                                                                       ', '243                 '),
  ('91', 'GERONY                                                                          ', 'CAROLE                                                                          ', '229                 '),
  ('92', 'GESSE                                                                           ', 'MARIE CLAIRE                                                                    ', '230                 '),
  ('93', 'GUIRESSE                                                                        ', 'BRIGITTE                                                                        ', '203                 '),
  ('94', 'ORDUNA                                                                          ', 'PIERRE                                                                          ', 'PRODUCTION          '),
  ('95', 'EPELVA                                                                          ', 'François                                                                        ', 'PRODUCTION          '),
  ('96', 'PICOT                                                                           ', 'FREDERIC                                                                        ', 'PRODUCTION          '),
  ('97', 'DOS SANTOS                                                                      ', 'Elisa                                                                           ', 'ADMIN               '),
  ('99', 'MOUREU                                                                          ', 'MARIE LAURE                                                                     ', '201                 '),
  ('101', 'CAZENAVE                                                                        ', 'JEAN                                                                            ', 'PRODUCTION          '),
  ('102', 'LEPOLARD                                                                        ', 'Aurélien, Michel                                                                ', '                    '),
  ('103', 'POLI                                                                            ', 'Xabi, Saint, Martin                                                             ', 'PRODUCTION          '),
  ('104', 'DENECKER                                                                        ', 'Charlotte                                                                       ', 'ADMIN               '),
  ('105', 'HEGUIABEHERE                                                                    ', 'Alexandre                                                                       ', 'PRODUCTION          '),
  ('106', 'REMON                                                                           ', 'Florian                                                                         ', 'PRODUCTION          '),
  ('107', 'FERNANDEZ                                                                       ', 'Thomas                                                                          ', 'PRODUCTION          '),
  ('108', 'BARAT                                                                           ', 'Romain                                                                          ', 'ADMIN               '),
  ('109', 'DUTTER                                                                          ', 'Muriel                                                                          ', 'LABO                '),
  ('110', 'OYHENART                                                                        ', 'Nicolas                                                                         ', 'PRODUCTION          '),
  ('111', 'BERRETEROT                                                                      ', 'Julien                                                                          ', 'PRODUCTION          '),
  ('112', 'GONOT                                                                           ', 'Damien                                                                          ', 'PRODUCTION          '),
  ('113', 'CAPURET                                                                         ', 'Anthony                                                                         ', 'PRODUCTION          '),
  ('114', 'RABINEAU                                                                        ', 'Nicolas                                                                         ', 'ADMIN               '),
  ('115', 'DESLANDES                                                                       ', 'Laurent                                                                         ', 'PRODUCTION          '),
  ('116', 'ERBIN                                                                           ', 'Julien                                                                          ', 'PRODUCTION          '),
  ('117', 'LEPOLARD                                                                        ', 'Baptiste                                                                        ', 'PRODUCTION          '),
  ('118', 'AREN                                                                            ', 'Pierre                                                                          ', 'PRODUCTION          '),
  ('119', 'LAUGA                                                                           ', 'Frédéric                                                                        ', 'PRODUCTION          '),
  ('120', 'CAMPANE                                                                         ', 'Lionel                                                                          ', 'PRODUCTION          '),
  ('121', 'DUMOLLARD                                                                       ', 'Thierry                                                                         ', 'PRODUCTION          '),
  ('122', 'JELASSI                                                                         ', 'Joël-Jean                                                                       ', 'MAINTENANCE         '),
  ('123', 'MILAGE                                                                          ', 'Alban                                                                           ', 'PRODUCTION          '),
  ('124', 'DUMUR-LOURTEAU                                                                  ', 'Vincent                                                                         ', 'PRODUCTION          '),
  ('125', 'RAMONTEU-CHIROS                                                                 ', 'Ludovic                                                                         ', 'PRODUCTION          '),
  ('126', 'HAVY                                                                            ', 'Floriant                                                                        ', 'PRODUCTION          '),
  ('127', 'DEVERITE                                                                        ', 'Jonathan                                                                        ', 'PRODUCTION          '),
  ('129', 'LARROQUE                                                                        ', 'GUILLAUME                                                                       ', 'MAINTENANCE         '),
  ('130', 'DOS SANTOS                                                                      ', 'CHARLY                                                                          ', 'PRODUCTION 1404     '),
  ('131', 'RICE                                                                            ', 'MATTHEW                                                                         ', 'PRODUCTION          '),
  ('132', 'PEYROU                                                                          ', 'Maxime                                                                          ', 'PRODUCTION          '),
  ('133', 'LASCOUMES                                                                       ', 'MARIE                                                                           ', 'ADMIN               '),
  ('134', 'SALMON                                                                          ', 'Quentin                                                                         ', 'PRODUCTION          '),
  ('135', 'EL HAMOUCHI                                                                     ', 'Mohamed                                                                         ', 'LABORATOIRE         '),
  ('136', 'CHAMMAM                                                                         ', 'Marwa                                                                           ', 'ADMINISTRATIF       '),
  ('137', 'REBIERE                                                                         ', 'Théo, Romain                                                                    ', 'R&D                 '),
  ('138', 'DENNEMONT                                                                       ', 'Valentin                                                                        ', 'PRODUCTION          '),
  ('139', 'COURTIES                                                                        ', 'Paul, Marc                                                                      ', 'PRODUCTION          ');

INSERT INTO import_personnel (PINDIVIDU_ID, NOMFAMILLE, PRENOM, NUMPOSTE) VALUES
  ('140', 'GOUVINHAS                                                                       ', 'Alexandre                                                                       ', 'PRODUCTION          '),
  ('141', 'LUQUET                                                                          ', 'François                                                                        ', 'PRODUCTION          '),
  ('142', 'POISSONNET                                                                      ', 'Jean-Louis                                                                      ', 'PRODUCTION          '),
  ('143', 'BIDONDO                                                                         ', 'Anthony                                                                         ', 'PRODUCTION          '),
  ('144', 'UNANUA                                                                          ', 'Dominique                                                                       ', 'PRODUCTION          '),
  ('145', 'DEVAUX                                                                          ', 'David                                                                           ', 'PRODUCTION          '),
  ('146', 'GONZALEZ MERG                                                                   ', 'Paulo Cristiano                                                                 ', 'PRODUCTION          '),
  ('147', 'LOUREIRO                                                                        ', 'Michel                                                                          ', 'PRODUCTION          '),
  ('148', 'SERVANT                                                                         ', 'Mikaël                                                                          ', 'PRODUCTION          '),
  ('149', 'FERNANDEZ                                                                       ', 'Yohan                                                                           ', 'PRODUCTION          '),
  ('150', 'PELEGRINELLI                                                                    ', 'Damien                                                                          ', 'PRODUCTION          '),
  ('151', 'DAVIES                                                                          ', 'Edouard                                                                         ', 'PRODUCTION          '),
  ('152', 'SALLETTE                                                                        ', 'Frédéric                                                                        ', 'PRODUCTION          '),
  ('153', 'COURTIES                                                                        ', 'Clérik                                                                          ', 'PRODUCTION          '),
  ('154', 'DUCHAMP                                                                         ', 'Lionel                                                                          ', 'PRODUCTION          '),
  ('155', 'SAIZ FERNANDEZ                                                                  ', 'Kévin                                                                           ', 'PRODUCTION          '),
  ('156', 'ETCHEVERRY                                                                      ', 'Fabien                                                                          ', 'PRODUCTION          '),
  ('157', 'TARDY                                                                           ', 'Maxime                                                                          ', 'PRODUCTION          '),
  ('158', 'CAMPANE                                                                         ', 'Jean-François                                                                   ', 'PRODUCTION          '),
  ('159', 'BERGERON                                                                        ', 'Marie-Noële                                                                     ', 'LABORATOIRE         '),
  ('160', 'MUNOZ TERES                                                                     ', 'Vanessa                                                                         ', 'QUALITE             '),
  ('161', 'DA COSTA-RAMOS                                                                  ', 'Sergio                                                                          ', 'PRODUCTION          '),
  ('162', 'CARRICABURU                                                                     ', 'Alain                                                                           ', '                    '),
  ('163', 'CHARDIN                                                                         ', 'Kévin                                                                           ', '                    '),
  ('164', 'MARTA                                                                           ', 'Frédéric                                                                        ', '                    '),
  ('165', 'ACEDO                                                                           ', 'Sébastien                                                                       ', '                    '),
  ('166', 'LOUSTALOT                                                                       ', 'Marlène                                                                         ', 'Cariste-HSE         '),
  ('167', 'BRANA                                                                           ', 'Jean-Paul                                                                       ', 'PRODUCTION          '),
  ('168', 'ETCHEBERRIBORDE                                                                 ', 'Julie                                                                           ', 'ADMIN               '),
  ('169', 'DA COSTA SILVA                                                                  ', 'Sonia                                                                           ', '                    '),
  ('170', 'MOSQUEDA                                                                        ', 'Martin                                                                          ', '                    '),
  ('171', 'GELARD                                                                          ', 'Alain                                                                           ', '                    '),
  ('172', 'IDIART                                                                          ', 'Céline                                                                          ', 'ADMINISTRATIF       '),
  ('173', 'MORIAT                                                                          ', 'André                                                                           ', 'PRODUCTION          '),
  ('174', 'ETCHEVERRY                                                                      ', 'Adrien                                                                          ', '                    '),
  ('175', 'MICHAUT                                                                         ', 'Bettan                                                                          ', 'MAINTENANCE         '),
  ('176', 'POUTOU                                                                          ', 'Eldon                                                                           ', 'PRODUCTION          '),
  ('177', 'MERCIRIS                                                                        ', 'Théo                                                                            ', 'PRODUCTION          '),
  ('178', 'MARCADIEU                                                                       ', 'Cédric                                                                          ', 'PRODUCTION          '),
  ('179', 'THIERY                                                                          ', 'Adrien                                                                          ', 'Agent HSE - Cariste '),
  ('180', 'REVIDIEGO                                                                       ', 'Isabelle                                                                        ', 'Agent HSE           '),
  ('181', 'SAUVE                                                                           ', 'Amaïa                                                                           ', 'PRODUCTION          '),
  ('182', 'MONTOIS                                                                         ', 'Xabi                                                                            ', 'PRODUCTION          '),
  ('183', 'URRUTIA                                                                         ', 'Laurent                                                                         ', 'PRODUCTION          '),
  ('184', 'LAJOURNADE                                                                      ', 'Antoine                                                                         ', 'METHODE             '),
  ('185', 'BAGDASARIANI                                                                    ', 'Eduardi                                                                         ', 'PRODUCTION          '),
  ('186', 'BANQUET                                                                         ', 'Marine                                                                          ', 'QUALITE             '),
  ('187', 'FRETAY                                                                          ', 'Sabrina                                                                         ', 'HSE                 '),
  ('188', 'COLAS                                                                           ', 'Martin                                                                          ', 'ADMIN               '),
  ('189', 'ETCHEVERRIA                                                                     ', 'Joaquim                                                                         ', 'PRODUCTION          ');
