# -*- coding: utf-8 -*-


class TypeAlerte:
    """Types d'alertes disponibles."""
    CONTRAT_EXPIRE = "CONTRAT_EXPIRE"
    CONTRAT_EXPIRE_7J = "CONTRAT_EXPIRE_7J"
    CONTRAT_EXPIRE_30J = "CONTRAT_EXPIRE_30J"

    PERSONNEL_SANS_CONTRAT = "PERSONNEL_SANS_CONTRAT"
    PERSONNEL_SANS_COMPETENCES = "PERSONNEL_SANS_COMPETENCES"
    PERSONNEL_NOUVEAU_SANS_AFFECTATION = "PERSONNEL_NOUVEAU_SANS_AFFECTATION"
    PERSONNEL_SANS_MUTUELLE = "PERSONNEL_SANS_MUTUELLE"
    PERSONNEL_SANS_VISITE = "PERSONNEL_SANS_VISITE"
    PERSONNEL_SANS_ENTRETIEN = "PERSONNEL_SANS_ENTRETIEN"
